name: Deploy to Github Pages
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        
      - name: Set Node Environment
        uses: actions/setup-node@v3
        with:
             node-version: 'lts/*'
             
      - name: Update npm latest
        run: |
          npm install -g npm@latest 

      - name: Install and Build 🔧
        env:
          CI: false
        run: |
          echo node version "$(node -v)"
          echo npm version "$(npm --version)"
          npm install
          npm run demo-build
      
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.