name: Run tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Set Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Update npm latest
        run: |
          npm install -g npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Execute tests
        run: npm run test
